### ISSUE TITLE
sstore gas cost is 0??

### ISSUE THREAD

**Issue by robdoesstuff** [chronaeon/beigepaper#6]
Yellow paper says 20k for new storage, 5k to update storage and refund of 15k to clear storage. Has that changed?

**Comment by chronaeon** [comment]
Hey @robdoesstuff -- thanks for this issue.

The "0" gas cost is from the PyEthereum source file "opcodes.py." This was cited in References.bib, but not printed in the paper, so I've fixed that.

Here's the actual snippet: 
```
    0x54: ['SLOAD', 1, 1, 50],  # 200 now
    # actual cost 5000-20000 depending on circumstance
    0x55: ['SSTORE', 2, 0, 0],
```
I thought the 5000-20000 referred to SLOAD, but I wasn't sure since the 5000-20000 was in a comment, so I left it out. I checked the YP which also said 5000-20000. A lot of information in the Yellowpaper is theoretical only, so I decided to trust the client implementation's default "0" until someone could confirm otherwise.

Thanks for correcting this!
